# Configuration for development teams
language: 'en-US'

reviews:
  profile: 'assertive'
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - 'alpha'
      - 'beta'
      - 'main'
      - 'dev'
    ignore_title_keywords:
      - 'wip'
      - 'draft'
tools:
  eslint:
    enabled: true
  ruff:
    enabled: true
  gitleaks:
    enabled: true
  hadolint:
    enabled: true

chat:
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - '**/.cursorrules'
